### ISSUE TITLE
implement AOP based solution for tracking all API requests

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1461]
We need a way to track/audit all API requests coming into xpanse. The reason behind such a requirement is, most cloud providers write all service modification requests to specific systems. In case of Huawei cloud, the data is written to CTS service.

- [ ] Find a way to figure out how to extract for which CSP is the request intended to. Some available options -> make CSP a mandatory URI field in all POST, PUT and DELETE request, or add CSP as header, etc. 
- [ ] Use Spring AOP to `pointCut` all controller POST, PUT and DELETE methods.
- [ ] OrchestratorPlugin interface to have a new method -> auditApiRequest. This method must be to write a simple log line as  default implementation. 
- [ ] Audit only POST, PUT and DELETE requests. 

Please also discuss with @baixinsui about the

**Comment by WangLiNaruto** [comment]
let me do it
